title: Conifer Lodge
email: coniferlodge@gmail.com
description: >
  Nestled amongst the trees, Conifer Lodge is a huge custom home was made to
  accommodate the needs of your large group with ease.
url: "http://coniferlodge.us"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
